version: 2.1

orbs:
  docker: ledger/docker@volatile

workflows:
  build_test_and_publish:
    jobs:
      - docker/build_image:
          after_checkout:
            - run:
                name: Set version environment variable
                command: echo "export COMMIT_HASH=$(git rev-parse HEAD)" >> $BASH_ENV
          docker_build_args: --build-arg COMMIT_HASH
          filters:
            tags:
              only: /v.*/
      - docker/test_image:
          requires:
            - docker/build_image
          filters:
            tags:
              only: /v.*/
      - docker/publish_image:
          requires:
            - docker/test_image
          filters:
            branches:
              only:
                - master
                - master-drop2
                - develop
                - develop-drop2
                - release_candidate
                - release_candidate_drop2
            tags:
              only: /v.*/
